# Generated by Django 4.0.3 on 2022-08-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='media')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
